**Khóa học và tài liệu**

- https://web.stanford.edu/class/stats60/


**Sách**

- https://github.com/CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers




In [2]:
from IPython.display import IFrame
IFrame("https://nbviewer.jupyter.org/github/tiepvupsu/tiepvupsu.github.io/blob/master/ML_math.pdf",
       width=800, height=600)

# 1.Linear Algebra
**Basic**
- https://aivietnam.ai/courses/aisummer2019/lessons/dai-so-tuyen-tinh-co-ban/

**RL-Standford**

- http://cs229.stanford.edu/section/cs229-linalg.pdf

**VEF-ML course**


*   HW1-https://drive.google.com/file/d/1LyqGLUHqEd4EX8vLaU8wlG3GvBfaVflh/view




In [0]:
'''
Solutions
'''
from IPython.display import IFrame
IFrame("https://piazza-resources.s3.amazonaws.com/joewsz9eh732za/jon9ptnmgnau7/solutions_1.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIAR6AWVCBX2V2X222Q%2F20190811%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190811T153501Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Security-Token=AgoJb3JpZ2luX2VjEDMaCXVzLWVhc3QtMSJHMEUCIFfZR7fgpxKhlJiv0XdfPGAAVtVIjq52ID%2FBJTRuEjDDAiEAukFDV2XibRLZoM%2Fjc9NWDvca6A9FP%2BqD%2FA3tY9A4uE8q4wMIvP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARAAGgwxMzMxOTE1MDM5ODMiDJDLWloXUe2HGIAo1yq3A18pH9qHhM%2BaRj%2F7FnpgyQ0RUf9K4sg4KHHq3WwmdOsA7aRK9IDUDqvMa5QjgdnsD3BzQ1%2FRIOm8eHTRFoZrjjbQzx6ncBFRf9HJBs13gOtADx5j03y9i8wU0KgP5cDBo5PI0xPy2tCf63AOfkUxE50vWqXn8tAg6FqjiKsMe2x%2BaHsyAxiIP9qmgBZdaNyxO60%2F%2FarUKOpeGOyONTI2KnQiHKTh8Uxs9Sz%2FmypNBSoc%2FAbzYvBTItHm47H40MevvZhyb1piPf%2BF%2BXqiMmkazXCOFn2VrUZpEP3ZkgQxWL0BoLiKGPMCgPJxbjtewwI4C7apEvgfMkVEPUWamswV63qmy0leR6Ep1rRTHwMtNcjgy1Q7jH36%2FiB5eWEi5RZAOVL79U7%2FUPET97W6XS%2F%2F%2FkRzSYxE70L4uHBM83iARcjIPMISPHJ6o0xhq3yKhLsOm%2Bg1BRevV9hsNw5HkBigREbLugS%2Fbkp8k4ozrHuwYaGoBKZ8CpMpmaoctlHmylTa3JIombCgOaJO2hNJxak5pB1t%2BsED7O5a%2FCvkU4EgMv%2BPsC5KmKd1L4O6AZ05FimXz1S48yWJDRQwx%2BO%2F6gU6tAHmu8kq1XdRr0mMKoyMB0bCaJDjEsrdv0awB%2FiUwrQ0BYqD9Bj1q2WndT18g5T15zEdc2E%2BvssfWA3pNZBhhwc4Wu6i1cnJ5m6hDQZhI133D38gYcnjl%2BeBMH866AQO3HM39TTc1od5OtjB5heSG8P5ibnxwWZlktyDroFlvjkSqRwqlSx3E9gVJ8dJdfiqFVL%2BBICHFNYd8T%2B05l%2ByGxvzE%2FXvOx3soxN3u4qZxwIAyD5jKMs%3D&X-Amz-Signature=4d5430a088c8e91f575aabd58101776f95a4dd8612eb84ce5d0685c21a9bcf3b",
       width=1000, height=600)


# 2.Optimization

---




In [0]:
    
from IPython.display import IFrame

IFrame(src='https://metacademy.org/browse', width=1000, height=600)

# Convex Optimization
## Convex sets and convex function
* Machine Learning và Optimization có quan hệ mật thiết với nhau. Trong Optimization, Convex Optimization là quan trọng nhất. Một bài toán là convex optimization nếu hàm mục tiêu là convex và tập hợp các điểm thỏa mãn các điều kiện ràng buộc là một convex set.
*  Trong convex set, mọi đoạn thẳng nối hai điểm bất kỳ trong tập đó sẽ nằm hoàn toàn trong tập đó. Tập hợp các giao điểm của các convex sets là một convex set.
*  Một hàm số là convex nếu đoạn thẳng nối hai điểm bất kỳ trên đồ thì hàm số đó không nằm dưới đồ thị đó.
*  Một hàm số khả vi là convex nếu tập xác định của nó là convex và đường (mặt) tiếp tuyến không nằm phía trên đồ thị (bề mặt) của hàm số đó.
*  Các norms là các hàm lồi, được sử dụng nhiều trong tối ưu.

## Convex Optimization Problem
*  Các bài toán tối ưu xuất hiện rất nhiều trong thực tế, trong đó Tối Ưu Lồi đóng một vai trò quan trọng. Trong bài toán Tối Ưu Lồi, nếu tìm được cực trị thì cực trị đó chính là một điểm optimal của bài toán (nghiệm của bài toán).
*  Có nhiều bài toán tối ưu không được viết dưới dạng convex nhưng có thể biến đổi về dạng convex, ví dụ như bài toán Geometric Programming.
*  Linear Programming và Quadratic Programming đóng một vài trò quan trọng trong toán tối ưu, được sử dụng nhiều trong các thuật toán Machine Learning.
*  Thư viện CVXOPT được dùng để tối ưu nhiều bài toán tối ưu lồi, rất dễ sử dụng và thời gian chạy tương đối nhanh.

## Duality
* Các bài toán tối ưu với chỉ ràng buộc là đẳng thức có thể được giải quyết bằng phương pháp nhân tử Lagrange. Ta cũng có định nghĩa về Lagrangian. Điều kiện cần để một điểm là nghiệm của bài toán tối ưu là nó phải làm cho đạo hàm của Lagrangian bằng 0.


source
[1](https://machinelearningcoban.com/2017/03/12/convexity/),
[pdf](https://nbviewer.jupyter.org/github/tiepvupsu/tiepvupsu.github.io/blob/master/assets/latex/book_CVX.pdf)

## Gradient descent

Source:
[1](https://machinelearningcoban.com/2017/01/16/gradientdescent2/#-batch-gradient-descent),
[2](http://ruder.io/optimizing-gradient-descent/index.html)-fullGD,


### Classic (batch) Gradient descent

Ý tưởng: tìm tối ưu bằng cách di chuyển ngược đạo hàm.
- batch (tất cả), sử dụng tất cả các điểm dữ liệu để tính đạo hàm mỗi lần cập nhật 
- mini-batch (1 sample đại điện), sử dụng tất cả các điểm dữ liệu trong 1 sample đại diện (có thể lấy bằng ngẫu nhiên, hoặc lấy khoảng) để tính đạo hàm mỗi lần cập nhật 







Consider a convex quadratic function in n-dimensional space of the form

$$f(x) = \frac{1}{2}\mathrm x^TA\mathrm x + b^T\mathrm x,$$

where A is a symmetric, positive semidefinite matrix of size $n \times n$ and b is a vector
of size $n$. Write a Python program that takes A and b as inputs and optimizes
function f using Gradient Descent algorithm. Note: initialization is important.
<br>
<br>

**Solution:** Access [here](https://colab.research.google.com/drive/190GPiQz4yQHTPYKH41BoFoT9Ugr1hWFP) for IPYTHON viewing

From the question, we have that $f$ is a *convex* quadratic function

$$f (\mathrm x) := \frac 12 \mathrm x^\top \mathrm A \,\mathrm x + \mathrm b^\top \mathrm x$$

where matrix $\rm A$ is symmetric and positive semidefinite. The gradient of $f$ is

$$\nabla f (\mathrm x) = \mathrm A \mathrm x + \mathrm b$$

Using **gradient descent** with step $\mu$,

$$\begin{array}{rl}\mathrm x_{k+1} &= \mathrm x_k - \mu \nabla f (\mathrm x_k)\\ &= \mathrm x_k - \mu \left( \mathrm A \mathrm x_k - \mathrm b \right)\\ &= \left( \mathrm I - \mu \mathrm A \right) \mathrm x_k + \mu \mathrm b\end{array}$$

Finanlly, choose step $\mu$ such that the (real) eigenvalues of $\mathrm I - \mu \mathrm A$ are in the open interval $(-1,1)$.
Remark that A should be the symmetric positive semidefinite matrix

#### Exp 1

In [0]:
import numpy as np

In [0]:
# function for generating A,b 
def gen_Ab(size):
  A = np.random.randint(0,5, size=(size, size))
  A = np.dot(A,A.transpose()) #for sure that A is positive semidefinite 
  A = (A + A.T)/2  # for sure that A is symmetric
  b = np.random.randint(0,5, size=(size, 1))
  print('matrix A')
  for x in A:
    print(*x, sep=" ")
  print('\nb:')
  for x in b.transpose():
    print(*x, sep=" ")
  return A,b

In [0]:
# example 2x2 matrix
A,b = gen_Ab(2)

matrix A
2.0 2.0
2.0 4.0

b:
2 4


In [0]:
def gradient_descent(A, b, mu, num_iters, threshold): 
  n = A.shape[0]
  x = np.random.randint(10, size=(n, 1))
  array_x = []
  array_fx = []
  array_x.append(x)  
  array_fx.append(1/2*np.dot(np.dot(x.transpose(),A),x) 
                       + np.dot(b.transpose(),x))
  
  for i in range(0, num_iters):
    delta_fx =  np.dot(A,x) + b  
    x = x - mu*delta_fx
    fx = np.around((1/2*np.dot(np.dot(x.transpose(),A),x) + np.dot(b.transpose(),x)),9)    
    if i == 0:
      array_x.append(x) 
      array_fx.append(fx)
    else:
        #array_x.append(x) 
        #array_fx.append([fx])
      if abs(fx - array_fx[i-1]) >= threshold:
        array_x.append(x) 
        array_fx.append(fx)
      else:
        break                
 
  return array_x,array_fx
  

In [0]:
# A is matrix 1x1
A,b = gen_Ab(1)
x, fx = gradient_descent(A, b, 0.1, 1000, 10**(-9))

matrix A
4.0

b:
4


In [0]:
x[-10:-1]

[array([[-0.99939064]]),
 array([[-0.99963438]]),
 array([[-0.99978063]]),
 array([[-0.99986838]]),
 array([[-0.99992103]]),
 array([[-0.99995262]]),
 array([[-0.99997157]]),
 array([[-0.99998294]]),
 array([[-0.99998977]])]

In [0]:
print('Number of gradient steps: %d' %len(fx))
print('fx has minimum value = %s' %fx[-1])
fx[-10:-1]


Number of gradient steps: 29
fx has minimum value = [[-2.]]


[array([[-1.99999926]]),
 array([[-1.99999973]]),
 array([[-1.9999999]]),
 array([[-1.99999996]]),
 array([[-1.99999999]]),
 array([[-2.]]),
 array([[-2.]]),
 array([[-2.]]),
 array([[-2.]])]

In [0]:
A,b = gen_Ab(2)

matrix A: [[4. 4.]
 [4. 8.]]
vector b: [[0 3]]


In [0]:
# A is matrix 2x2
A,b = gen_Ab(2)
x, fx = gradient_descent(A, b, 0.01, 1000, 10**(-9))

matrix A
18.0 18.0
18.0 20.0

b:
0 1


In [0]:
x[-10:-1]

[array([[ 0.49976283],
        [-0.49977564]]), array([[ 0.49976514],
        [-0.49977782]]), array([[ 0.49976742],
        [-0.49977998]]), array([[ 0.49976968],
        [-0.49978212]]), array([[ 0.49977192],
        [-0.49978424]]), array([[ 0.49977414],
        [-0.49978634]]), array([[ 0.49977633],
        [-0.49978841]]), array([[ 0.49977851],
        [-0.49979047]]), array([[ 0.49978066],
        [-0.49979251]])]

In [0]:
print('Number of gradient steps: %d' %len(fx))
print('fx has minimum value = %s' %fx[-1])
fx[-10:-1]


Number of gradient steps: 736
fx has minimum value = [[-0.24999996]]


[array([[-0.24999995]]),
 array([[-0.24999995]]),
 array([[-0.24999995]]),
 array([[-0.24999995]]),
 array([[-0.24999995]]),
 array([[-0.24999995]]),
 array([[-0.24999995]]),
 array([[-0.24999995]]),
 array([[-0.24999996]])]

In [0]:
z = np.linalg.solve(A, -b)
z

array([[ 0.5],
       [-0.5]])

In [0]:
np.around((1/2*np.dot(np.dot(z.transpose(),A),z) + np.dot(b.transpose(),z)),9)  

array([[-0.25]])

In [0]:
# A is matrix 3x3
A,b = gen_Ab(3)

matrix A
41.0 18.0 16.0
18.0 9.0 8.0
16.0 8.0 16.0

b:
2 4 1


In [0]:
x, fx = gradient_descent(A, b, 0.03, 1000, 10**(-9))

In [0]:
print('Number of gradient steps: %d' %len(fx))
print('fx has minimum value = %s' %fx[-1])
fx[-10:-1]


Number of gradient steps: 377
fx has minimum value = [[-4.85624999]]


[array([[-4.85624999]]),
 array([[-4.85624999]]),
 array([[-4.85624999]]),
 array([[-4.85624999]]),
 array([[-4.85624999]]),
 array([[-4.85624999]]),
 array([[-4.85624999]]),
 array([[-4.85624999]]),
 array([[-4.85624999]])]

In [0]:
# A is matrix 4x4
A,b = gen_Ab(4)

matrix A
34.0 27.0 9.0 14.0
27.0 35.0 9.0 14.0
9.0 9.0 6.0 6.0
14.0 14.0 6.0 12.0

b:
1 2 3 4


In [0]:
x, fx = gradient_descent(A, b, 0.001, 10000, 10**(-9))

In [0]:
print('After %d gradient steps' %len(fx))
print('fx has minimum value = %s\n' %fx[-1])
fx[-10:-1]


After 4014 gradient steps
fx has minimum value = [[-1.43877531]]



[array([[-1.4387753]]),
 array([[-1.4387753]]),
 array([[-1.4387753]]),
 array([[-1.43877531]]),
 array([[-1.43877531]]),
 array([[-1.43877531]]),
 array([[-1.43877531]]),
 array([[-1.43877531]]),
 array([[-1.43877531]])]

#### Exp 2

In [0]:
import numpy as np
def objective(A,b,x):
  return(np.dot(x.T,np.dot(A,x)))+np.dot(b,x)

def gradientdescent(A,b,stepSize=0.01,niters=1000,epsilon=0.01):
  n=A.shape[0]
  x=np.random.rand(n)
  for i in range(niters):
    print("iteration %d"%(i)) 
    grad=np.dot(A,x)+ b 
    print("gradient norm = %.4f"%(np.linalg.norm(grad)))
    print("    function value = %.4f"%(objective(A,b,x)))
    if np.linalg.norm(grad) < epsilon:
      print("∗∗∗optimal solution found")
      break 
    x = x - stepSize*grad
    print('−−−')
  return x,objective(A,b,x)
#
A=np.array([[1,0,0],[0,1,0],[0,0,1]])
b=np.array([0,0,0])
x,obj = gradientdescent(A,b)
print("\n\n\nbest solution found:{}".format(x))
print("best objective value:{}".format(obj))

iteration 0
gradient norm = 1.4577
    function value = 2.1250
−−−
iteration 1
gradient norm = 1.4432
    function value = 2.0827
−−−
iteration 2
gradient norm = 1.4287
    function value = 2.0412
−−−
iteration 3
gradient norm = 1.4144
    function value = 2.0006
−−−
iteration 4
gradient norm = 1.4003
    function value = 1.9608
−−−
iteration 5
gradient norm = 1.3863
    function value = 1.9218
−−−
iteration 6
gradient norm = 1.3724
    function value = 1.8836
−−−
iteration 7
gradient norm = 1.3587
    function value = 1.8461
−−−
iteration 8
gradient norm = 1.3451
    function value = 1.8093
−−−
iteration 9
gradient norm = 1.3317
    function value = 1.7733
−−−
iteration 10
gradient norm = 1.3183
    function value = 1.7380
−−−
iteration 11
gradient norm = 1.3052
    function value = 1.7034
−−−
iteration 12
gradient norm = 1.2921
    function value = 1.6696
−−−
iteration 13
gradient norm = 1.2792
    function value = 1.6363
−−−
iteration 14
gradient norm = 1.2664
    function value = 1

### Stochastic Gradient Descent
Ý tưởng: tìm tối ưu bằng cách di chuyển ngược đạo hàm.
- stochastic (ngẫu nhiên), chỉ xử dụng 1 điểm dữ liệu $x+i$ để tính đạo hàm rồi cập nhật GD

có code mẫu ở trang MLc cơ bản

### Tiêu chí khác
## Các thuật toán tối ưu Gradient Descent
- Momentum: ý tưởng là khi cho thêm 1 đại lượng vận tốc, để khi gặp local-minimun hàm GD có thể vượt qua, và thực sự hội tụ ở global-minimum. *Lượng thay đổi* = tổng hai vector momentum vector và gradient ở hiện tại
- Nesterov accelerated gradient (NAG): giải quyết đà của momentum để hội tụ nhanh hơn, điều chỉnh *lượng thay đổi*  = tổng hai vector momentum vector và gradient ở thời điểm được xấp xỉ là điểm tiếp theo

## Stopping Criteria (điều kiện dừng)

Có một điểm cũng quan trọng mà từ đầu tôi chưa nhắc đến: khi nào thì chúng ta biết thuật toán đã hội tụ và dừng lại?

Trong thực nghiệm, có một vài phương pháp như dưới đây:

*  Giới hạn số vòng lặp: đây là phương pháp phổ biến nhất và cũng để đảm bảo rằng chương trình chạy không quá lâu. Tuy nhiên, một nhược điểm của cách làm này là có thể thuật toán dừng lại trước khi đủ gần với nghiệm.
*  So sánh gradient của nghiệm tại hai lần cập nhật liên tiếp, khi nào giá trị này đủ nhỏ thì dừng lại. Phương pháp này cũng có một nhược điểm lớn là việc tính đạo hàm đôi khi trở nên quá phức tạp (ví dụ như khi có quá nhiều dữ liệu), nếu áp dụng phương pháp này thì coi như ta không được lợi khi sử dụng SGD và mini-batch GD.
*  So sánh giá trị của hàm mất mát của nghiệm tại hai lần cập nhật liên tiếp, khi nào giá trị này đủ nhỏ thì dừng lại. Nhược điểm của phương pháp này là nếu tại một thời điểm, đồ thị hàm số có dạng bẳng phẳng tại một khu vực nhưng khu vực đó không chứa điểm local minimum (khu vực này thường được gọi là saddle points), thuật toán cũng dừng lại trước khi đạt giá trị mong muốn.
*  Trong SGD và mini-batch GD, cách thường dùng là so sánh nghiệm sau một vài lần cập nhật. Trong đoạn code Python phía trên về SGD, tôi áp dụng việc so sánh này mỗi khi nghiệm được cập nhật 10 lần. Việc làm này cũng tỏ ra khá hiệu quả.


### Discuss and code
[1](https://machinelearningcoban.com/2017/01/16/gradientdescent2/#-cac-thuat-toan-toi-uu-gradient-descent)

## Newton’s method

# 3.Probability
**RL-Standford**

- http://cs229.stanford.edu/section/cs229-prob.pdf

**VEF-ML**

- VEF-[HW2 - General Probability](https://piazza-resources.s3.amazonaws.com/joewsz9eh732za/jooz16tbwt4381/HW_2.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIAR6AWVCBXQV3LK55Z%2F20190811%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190811T155612Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Security-Token=AgoJb3JpZ2luX2VjEDQaCXVzLWVhc3QtMSJHMEUCIQC23VphLywkz%2BqhRKJeBYI2kNH78ukglfgKZGiIQ3UFmQIgICPELbRf91SZ3mLNXmq5JLwQLMm0JyqxfmXWG%2FWfcp0q4wMIvP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARAAGgwxMzMxOTE1MDM5ODMiDKI48V%2FKrlL0N2jsvyq3AzvVGse5DCKGdgp5%2BtA%2Fn6wUuwI0sb44vJXE4C5JC9vQn4uiZV5WBmszGQqrStuABTYt1KZBmWPA7xAG8SHtdMgUWxHgAb3bO8DpiDwOv2e8wE1SxYbzrXVSy03D%2B3VbuRYzxQHCP2qTSE9kXCQjP47OE1hndbs5wqg5V5K228XhV9%2FADzkbdA1KXMijGZLiMOoyxwIQFR5uA3hyL3mQDHZkOYC4Y6SY4BbDCdzRjr4Bnj71T5LrGCZMQzlkkFss4mg0rqtUmLZKEo7WbJD4c4YxnWq4GaK4GRiVPsE7JmUTVU08zZp%2FOvFpChKxDEFdAXsl0upsVY%2F25kjYsI1dNWgvF%2FzzOqTgpXxp26hh9hnkp5QBJe3WxpbfWe7yMOA6sluoV97D%2B6%2FODN5Hjx3nm%2FFIXhoy6a6y%2BO4g6nN32goD4t1IlzLo4UAYhXQwsBM7GIY26b8ERhCaqpUmW5iw7DGn6sdpLjdSXfkuO%2BpIYQQrFJ3BXrTFW7aX97VEb%2B1dDCTHDc3we8%2B1KfvAT1ZTqEsxt180dTH5GXUbu40qnJYzoIYvEhryuUGPVWp3Bz0H%2BAf5QWvICAQw9%2FG%2F6gU6tAGdHWqEEHLgpZ4JDdngtjN4ycxOpUuavPxBWWckwHdf9FVchAoTxNawDLYp5GYkkWgcFlLITNANSwR0UyHih5vgr29VL5rv3%2BDxcOqfWRHJ1x7x%2FmMJlqReVF%2FLjhETfHH0ov5Ge2vt6m%2FWvswKZ1R5aMi1Ek7LG4kSOxWrt6o27VjN2v1JmyfVVndgSyn%2BrGOiJyfPowsOHphPXRV%2BSeugs5wyJ1%2BYrlpfhSWvlrCpZbwNtTE%3D&X-Amz-Signature=6ec31dcf70a5fa71782a1b3f9a6e06cb4c20970aa5709323225cf619aac64aa1) - [Solution](https://piazza-resources.s3.amazonaws.com/joewsz9eh732za/jpk651z4wbh27r/solutions_2.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIAR6AWVCBXQV3LK55Z%2F20190811%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190811T155615Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Security-Token=AgoJb3JpZ2luX2VjEDQaCXVzLWVhc3QtMSJHMEUCIQC23VphLywkz%2BqhRKJeBYI2kNH78ukglfgKZGiIQ3UFmQIgICPELbRf91SZ3mLNXmq5JLwQLMm0JyqxfmXWG%2FWfcp0q4wMIvP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARAAGgwxMzMxOTE1MDM5ODMiDKI48V%2FKrlL0N2jsvyq3AzvVGse5DCKGdgp5%2BtA%2Fn6wUuwI0sb44vJXE4C5JC9vQn4uiZV5WBmszGQqrStuABTYt1KZBmWPA7xAG8SHtdMgUWxHgAb3bO8DpiDwOv2e8wE1SxYbzrXVSy03D%2B3VbuRYzxQHCP2qTSE9kXCQjP47OE1hndbs5wqg5V5K228XhV9%2FADzkbdA1KXMijGZLiMOoyxwIQFR5uA3hyL3mQDHZkOYC4Y6SY4BbDCdzRjr4Bnj71T5LrGCZMQzlkkFss4mg0rqtUmLZKEo7WbJD4c4YxnWq4GaK4GRiVPsE7JmUTVU08zZp%2FOvFpChKxDEFdAXsl0upsVY%2F25kjYsI1dNWgvF%2FzzOqTgpXxp26hh9hnkp5QBJe3WxpbfWe7yMOA6sluoV97D%2B6%2FODN5Hjx3nm%2FFIXhoy6a6y%2BO4g6nN32goD4t1IlzLo4UAYhXQwsBM7GIY26b8ERhCaqpUmW5iw7DGn6sdpLjdSXfkuO%2BpIYQQrFJ3BXrTFW7aX97VEb%2B1dDCTHDc3we8%2B1KfvAT1ZTqEsxt180dTH5GXUbu40qnJYzoIYvEhryuUGPVWp3Bz0H%2BAf5QWvICAQw9%2FG%2F6gU6tAGdHWqEEHLgpZ4JDdngtjN4ycxOpUuavPxBWWckwHdf9FVchAoTxNawDLYp5GYkkWgcFlLITNANSwR0UyHih5vgr29VL5rv3%2BDxcOqfWRHJ1x7x%2FmMJlqReVF%2FLjhETfHH0ov5Ge2vt6m%2FWvswKZ1R5aMi1Ek7LG4kSOxWrt6o27VjN2v1JmyfVVndgSyn%2BrGOiJyfPowsOHphPXRV%2BSeugs5wyJ1%2BYrlpfhSWvlrCpZbwNtTE%3D&X-Amz-Signature=485f76b6ec74313f0c315a1abada42e761cc20cdcdab1f97663e038e70a9e7a2)




## Maximum likelihood
chương 4 sách ML cơ bản